import Head from "next/head";
import Navbar from "@/components/navbar/navbar";
import HeroSection from "@/components/sections/heroSection/heroSection";
import SideElement from "@/components/sideElement/sideElement";
import SocialLink from "@/components/sideElement/socialLink/socialLink";
import EmailLink from "@/components/sideElement/emailLink/emailLink";
import AboutMeSection from "@/components/sections/aboutMeSection/aboutMeSection";
import styles from "./index.module.scss";
import ExperienceSection from "@/components/sections/experienceSection/experienceSection";
import ProjectSection from "@/components/sections/projectSection/projectSection";
import ContactSection from "@/components/sections/contactSection/contactSection";
export default function Home() {
  return (
    <>
      <Head>
        <title>Jeff Ou - Full Stack Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={styles.main}>
        <HeroSection></HeroSection>
        <AboutMeSection></AboutMeSection>
        <ExperienceSection></ExperienceSection>
        <ProjectSection></ProjectSection>
        <ContactSection></ContactSection>
      </main>

      <SideElement left>
        <SocialLink></SocialLink>
      </SideElement>
      <SideElement>
        <EmailLink></EmailLink>
      </SideElement>
    </>
  );
}
