import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import Hero from "@/components/hero/hero";
import SideElement from "@/components/sideElement/sideElement";
import SocialLink from "@/components/sideElement/socialLink/socialLink";
import EmailLink from "@/components/sideElement/emailLink/emailLink";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Hero></Hero>
      <SideElement left>
        <SocialLink></SocialLink>
      </SideElement>
      <SideElement>
        <EmailLink></EmailLink>
      </SideElement>
    </>
  );
}
